macro_rules! invoke_handler {
    () => {
        tauri::generate_handler![
            // service
            crate::commands::service::service_start,
            crate::commands::service::service_stop,
            crate::commands::service::service_initialize,
            crate::commands::service::service_rpc_token,
            crate::commands::startup::service_startup_snapshot,
            crate::commands::stats::service_stats_cost_summary,
            crate::commands::stats::service_stats_cost_export,
            crate::commands::stats::service_stats_cost_model_pricing_get,
            crate::commands::stats::service_stats_cost_model_pricing_set,
            crate::commands::stats::service_stats_trends_requests,
            crate::commands::stats::service_stats_trends_models,
            crate::commands::stats::service_stats_trends_heatmap,
            // audit
            crate::commands::audit::service_audit_list,
            crate::commands::audit::service_audit_export,
            // alert
            crate::commands::alert::service_alert_rules_list,
            crate::commands::alert::service_alert_rules_upsert,
            crate::commands::alert::service_alert_rules_delete,
            crate::commands::alert::service_alert_channels_list,
            crate::commands::alert::service_alert_channels_upsert,
            crate::commands::alert::service_alert_channels_delete,
            crate::commands::alert::service_alert_channels_test,
            crate::commands::alert::service_alert_history_list,
            // account
            crate::commands::account::remote::service_account_list,
            crate::commands::account::remote::service_account_delete,
            crate::commands::account::remote::service_account_delete_many,
            crate::commands::account::remote::service_account_delete_unavailable_free,
            crate::commands::account::remote::service_account_delete_banned,
            crate::commands::account::remote::service_account_update,
            crate::commands::account::remote::service_account_update_many,
            crate::commands::account::remote::service_account_payment_generate_link,
            crate::commands::account::remote::service_account_subscription_check,
            crate::commands::account::remote::service_account_subscription_check_many,
            crate::commands::account::remote::service_account_subscription_mark,
            crate::commands::account::remote::service_account_payment_official_promo_link_set,
            crate::commands::account::remote::service_account_team_manager_upload,
            crate::commands::account::remote::service_account_team_manager_upload_many,
            crate::commands::account::remote::service_account_team_manager_test,
            crate::commands::account::transfer::service_account_import,
            crate::commands::account::transfer::service_account_import_by_file,
            crate::commands::account::transfer::service_account_import_by_directory,
            crate::commands::account::transfer::service_account_export_by_account_files,
            crate::commands::account::local::local_account_delete,
            // usage
            crate::commands::usage::service_usage_read,
            crate::commands::usage::service_usage_list,
            crate::commands::usage::service_usage_aggregate,
            crate::commands::usage::service_usage_refresh,
            // request log
            crate::commands::requestlog::service_requestlog_list,
            crate::commands::requestlog::service_requestlog_summary,
            crate::commands::requestlog::service_requestlog_export,
            crate::commands::requestlog::service_requestlog_clear,
            crate::commands::requestlog::service_requestlog_today_summary,
            // settings
            crate::commands::settings::service_listen::service_listen_config_get,
            crate::commands::settings::service_listen::service_listen_config_set,
            crate::commands::settings::gateway::service_gateway_route_strategy_get,
            crate::commands::settings::gateway::service_gateway_route_strategy_set,
            crate::commands::settings::gateway::service_gateway_manual_account_get,
            crate::commands::settings::gateway::service_gateway_manual_account_set,
            crate::commands::settings::gateway::service_gateway_manual_account_clear,
            crate::commands::settings::gateway::service_gateway_header_policy_get,
            crate::commands::settings::gateway::service_gateway_retry_policy_get,
            crate::commands::settings::gateway::service_gateway_retry_policy_set,
            crate::commands::settings::gateway::service_gateway_header_policy_set,
            crate::commands::settings::gateway::service_gateway_background_tasks_get,
            crate::commands::settings::gateway::service_healthcheck_config_get,
            crate::commands::settings::gateway::service_healthcheck_config_set,
            crate::commands::settings::gateway::service_healthcheck_run,
            crate::commands::settings::gateway::service_gateway_cache_stats,
            crate::commands::settings::gateway::service_gateway_cache_clear,
            crate::commands::settings::gateway::service_gateway_background_tasks_set,
            crate::commands::settings::gateway::service_gateway_upstream_proxy_get,
            crate::commands::settings::gateway::service_gateway_upstream_proxy_set,
            crate::commands::settings::gateway::service_gateway_freeproxy_sync,
            crate::commands::settings::gateway::service_gateway_transport_get,
            crate::commands::settings::gateway::service_gateway_transport_set,
            crate::commands::settings::web_auth::service_web_auth_two_factor_setup,
            crate::commands::settings::web_auth::service_web_auth_two_factor_verify,
            crate::commands::settings::web_auth::service_web_auth_two_factor_disable,
            crate::commands::settings::ui::app_settings_get,
            crate::commands::settings::ui::app_settings_set,
            crate::commands::settings::ui::app_close_to_tray_on_close_get,
            crate::commands::settings::ui::app_close_to_tray_on_close_set,
            // login
            crate::commands::login::service_login_start,
            crate::commands::login::service_login_status,
            crate::commands::login::service_login_complete,
            crate::commands::login::service_login_chatgpt_auth_tokens,
            crate::commands::login::service_account_read,
            crate::commands::login::service_account_logout,
            crate::commands::login::service_chatgpt_auth_tokens_refresh,
            crate::commands::login::service_account_auth_recover,
            // api key
            crate::commands::apikey::service_apikey_list,
            crate::commands::apikey::service_apikey_read_secret,
            crate::commands::apikey::service_apikey_rate_limit_get,
            crate::commands::apikey::service_apikey_rate_limit_set,
            crate::commands::apikey::service_apikey_model_fallback_get,
            crate::commands::apikey::service_apikey_model_fallback_set,
            crate::commands::apikey::service_apikey_allowed_models_get,
            crate::commands::apikey::service_apikey_allowed_models_set,
            crate::commands::apikey::service_apikey_response_cache_get,
            crate::commands::apikey::service_apikey_response_cache_set,
            crate::commands::apikey::service_apikey_create,
            crate::commands::apikey::service_apikey_models,
            crate::commands::apikey::service_apikey_usage_stats,
            crate::commands::apikey::service_apikey_update_model,
            crate::commands::apikey::service_apikey_delete,
            crate::commands::apikey::service_apikey_renew,
            crate::commands::apikey::service_apikey_disable,
            crate::commands::apikey::service_apikey_enable,
            // system
            crate::commands::system::open_in_browser,
            crate::commands::system::open_in_browser_incognito,
            crate::commands::system::app_window_unsaved_draft_sections_set,
            // updater
            crate::commands::updater::app_update_check,
            crate::commands::updater::app_update_prepare,
            crate::commands::updater::app_update_apply_portable,
            crate::commands::updater::app_update_launch_installer,
            crate::commands::updater::app_update_status
        ]
    };
}

pub(crate) use invoke_handler;
